# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: reflexion-data-pvc
#   namespace: kc-ai-research-lab
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Gi
#   storageClassName:
#     rook-ceph-block
#     # rook-ceph-block : Largest storage pool, works everywhere
#     # linstor-sdsu : Fastest possible I/O performance, provisioned in San Diego State University zone

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reflexion-data-pvc
  namespace: kc-ai-research-lab
spec:
  accessModes:
    - ReadWriteMany # ← changed
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-cephfs-central # ← changed from rook-ceph-block
